[build]
  functions = "functions"    # Directory for Netlify Functions
  publish = "dist"           # Directory to deploy (if you have a build directory)

[build.environment]
  DB_USERNAME = "admin"
  DB_PASSWORD = "omVzprqGwKgTyThL"
  GOOGLE_PASSWORD = "zghwoihpeurxnsio"
  SPARKPOST = "ef572ec5e2d59ce44fecd2daa40dc0103f587c95"
  TWILIO_ACCOUNT_SID = "AC3e2518ed1aa183fccaca7bdb341cda35"
  TWILIO_TOKEN = "8c0d70799c73f1498ae3f8376bd60846"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
