[build]
  functions = "functions",
  environment = {
    db_username = "billtrancon12",
    db_password = "LiamNgoan%40123"
  }

[dev]
  publish = "dist"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"